name: CI

on:
  pull_request:
  push:
    branches:
    - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    permissions:
      contents: read
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.13']
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install . --group dev
    - name: Run tests
      run: pytest -v
    - name: Build wheel and sdist
      run: |
        pip install build
        python -m build
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist-artifacts
        path: dist/

  release:
    name: Release
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags')
    needs: [test]
    runs-on: ubuntu-24.04
    environment:
      name: pypi
      url: https://pypi.org/p/vtk-xref
    permissions:
      id-token: write  # this permission is mandatory for trusted publishing
      contents: write  # required to create a release
    steps:
    - uses: actions/download-artifact@v4
    - name: Flatten directory structure
      run: |
        mkdir -p dist/
        find . -name '*.whl' -exec mv {} dist/ \;
        find . -name '*.tar.gz' -exec mv {} dist/ \;
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc
    - name: Create GitHub Release
      uses: softprops/action-gh-release@72f2c25fcb47643c292f7107632f7a47c1df5cd8
      with:
        generate_release_notes: true
        files: |
          ./**/*.whl
